### ISSUE TITLE
Please add the option to copy the original (non-flipped) character.

### ISSUE THREAD

**Issue by rkujawa** [marek-saji/flipping-cards#1]
Currently it is difficult to copy the character in non-flipped state (hiragana/katakana) to clipboard, as it is flipped immediately when mouse cursor is placed above it (hover). Sometimes it is desirable to copy the original character.

Maybe flipping could be inhibited by holding some keyboard key, or temporarily disabled by a button?

**Comment by marek-saji** [comment]
I'm working on a new version, where the copying won't be an issue. Hopefully I will find some time for that soon.

For now, as a workaround you can start selecting next to the card — that way you won't trigger the flip.

![recording2016-03-12t12 01 58](https://cloud.githubusercontent.com/assets/192323/13722582/adc7421a-e84a-11e5-8624-b6dc50d0dd00.gif)
