### ISSUE TITLE
Flipping does not work on mobile browsers due to lack of mouse cursor.

### ISSUE THREAD

**Issue by rkujawa** [marek-saji/flipping-cards#2]
Is it possible to add support for mobile browsers? Currently flipping does not work there (tested with Safari for iOS 9). I suspect this is due to mobile browser lacking cursor. On mobile flipping probably should be triggered by clicking onto the card.

**Comment by marek-saji** [comment]
Mobile Chrome simulates `:hover` on touch, I was convinced that Safari does the same, but looks like it's not. I've tried to make it work with `tabindex=1` and `:focus`, but surprisingly that does not work on mobile Safari. :( I really don't want to use JavaScript for something that trival.

**Comment by rkujawa** [comment]
Well, seems like using Chrome is a workaround for now. But maybe it should be user configurable, whether cards are to be flipped by hover or click?

**Comment by marek-saji** [comment]
Just wait a week and hopefully everything will get resolved in v1.0. {:

Out of curosity — does :hover simulation work in Chrome for iOS? I don't
have any real device at hand to test it, I'm using Browserstack, which has
only Safari on iOSes.

**Comment by marek-saji** [comment]
Closing, because it no longer apply to v1.0.0-alpha.
